### PR TITLE
Changed the way of getting the server address.

### PR DESCRIPTION
**Pull request by OhMyGuus**
This will hide the public IP form the website so you can use reverse proxies like Cloudflare. 

This was a request in the issue: #29

### CODE REVIEW

**Comment by djmattyg007** [comment]
I came looking for something along these lines. I don't really want the software I run to put unnecessary strain on public services such as ipify and icanhazip, which is what the `public-ip` package uses. It's also generally unnecessary for my use case - I'm going to put it behind a DNS record and don't need anything trying to be smart.

**Comment by mynameistito** [comment]
> This will hide the public IP form the website so you can use reverse proxies like Cloudflare. 
> 
> This was a request in the issue: #29 

Is this all needed? You can just edit where it says server IP or whatever the variable is with your domain within the index.pug within the views folder? 🤔

**Comment by OhMyGuus** [comment]
> > This will hide the public IP form the website so you can use reverse proxies like Cloudflare.
> > This was a request in the issue: #29
> 
> Is this all needed? You can just edit where it says server IP or whatever the variable is with your domain within the index.pug within the views folder? 🤔

When even the official Crewlink server (https://crewl.ink) changed the view it might be better to just update the repo itself. 
Also getting an IP through a package is not particularly privacy proof, since it will request an external service that can be logged.  

Even if those aren't problems in your eyes there is still a possible merge problem if u want to update the server.

**Comment by djmattyg007** [comment]
Why was this closed?

**Comment by OhMyGuus** [comment]
> Why was this closed?

Because Ottomated implemented it using a environment variable now (process.env.ADDRESS), so there is no chance it will be merged.

**Comment by djmattyg007** [comment]
Does the new change ensure third-party services aren't queried automatically through the "public ip" package?

**Pull request closed without merging**
