### PR TITLE
Support version 2020.12.3

### PR DESCRIPTION
**Pull request by vrnagy**
Add support for version 2020.12.3

Update for issue #9

### CODE REVIEW

**Comment by vrnagy** [comment]
Based on https://github.com/denverquane/amonguscapture/blob/master/Offsets.json

**Comment by DispatchCommit** [comment]
image

Might not be 100% correct for the offsets

**Comment by vrnagy** [comment]
Looks like not all offset was correct in the AmongUsCapture repository.
I can't reproduce this error, but I think one offset has to be changed, i'm currently trying to find the correct address

**Comment by DispatchCommit** [comment]
I actually cannot reproduce that error again either, so I'm not sure what caused it. I would try to help with finding offsets but I'm not familiar with how these were discovered, just trying to help with feedback and testing

**Comment by Denominator765** [comment]
One issue I have been able to find is that (at least for the meetingHud value) this file is using the hex value from the last version. Instead, it should be using 0x193BA9C

**Comment by vrnagy** [comment]
@Denominator765 @DispatchCommit made a new pull request wwith updated offsets. Can You test it maybe? https://github.com/ottomated/CrewLink-server/pull/11/files

**Comment by Denominator765** [comment]
Apologies for deleting my comment. I let doubt creep in and started worrying that I was wrong, but I have done my checking and can confirm that it was correct. For the purposes of not destroying comment history, the comment before @vrnagy was "One issue I have been able to find is that (at least for the meetingHud value) this file is using the hex value from the last version. Instead, it should be using 0x193BA9C"

**Pull request merged**
