### PR TITLE
Update 2020.12.3.yml

### PR DESCRIPTION
**Pull request by vrnagy**
The previous offsets in AmongUsCapture was wrong.
The have updatet to the correct ones.

Tested on private instance and worked fine

### CODE REVIEW

**Comment by sotif** [comment]
Can confirm this works.
Current offsets are incorrect.

**Comment by DispatchCommit** [comment]
image

I'm still seeing the UI stuck at the MENU screen. 

Here's what react shows is the current gamestate:

image

**Comment by D10100111001** [comment]
@DispatchCommit The offsets are probably cached to the wrong values. You might have to update the `config.json` file in your `%AppData%\crewlink` (Windows).

**Comment by filipmanzi** [comment]
@DispatchCommit I had to download the server repository then update the yml file with these new offsets in, then compile it. Then I had to open dev-tools-console and paste `(new (require('electron-store'))()).set('offsets', {})` in the CrewLink client, and restart.

**Comment by DispatchCommit** [comment]
Ah everytime I deleted the config file locally, it would fetch offsets from the ottomated server before I changed to localhost.

BUT THIS WORKS!!! I deleted just the offsets from my config file in appdata and relaunched, and can verify these offsets are correct :)

image

**Comment by SteefBew** [comment]
@filipmanzi is the console accessible from release version or would i need to build a dev version?

**Comment by vrnagy** [comment]
Looks like the player list offset is not correct. As You can see on the screenshot there is no player list in the client

**Comment by DispatchCommit** [comment]
@SteefBew just press ctrl-shift-i

**Comment by DispatchCommit** [comment]
@vrnagy no, I hadn't joined a filled lobby, it works fine

image

**Comment by vrnagy** [comment]
@DispatchCommit oh, i just tested with my PC and phone so only 2 player :D

**Comment by Denominator765** [comment]
Sorry it took me so long, but I just tested with two computers running the update and everything seems great!

**Pull request closed without merging**
